#props.put("bootstrap.servers", "192.168.2.4:9092");
#        props.put("group.id", "test");
#        props.put("enable.auto.commit", "true");
#        props.put("auto.commit.interval.ms", "1000");
#        props.put("key.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");
#        props.put("value.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");


#props.put("bootstrap.servers", "192.168.2.4:9092");
#        props.put("acks", "all");
#        props.put("retries", 0);
#        props.put("batch.size", 1000000);
#        props.put("linger.ms", 1);
#        props.put("buffer.memory", 33554432);
#        props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
#        props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

broker:
   servers: localhost:9092

topic:
   consumer:
      name: topic2
      groupId: group2
      enableAutoCommit: false
      autoCommitIntervalms: 1000
   com.samples.transfer:
      name: test
      acks: all
      retries: 0
      batchSize: 1
      bufferMemory: 10000000
